### PR TITLE
blog post: apt.llvm.org - moving from physical server to the cloud

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
I could not test the locally the rendering with images.
`hugo server -D` fails with:
```
Start building sites … 
hugo v0.88.0+extended linux/amd64 BuildDate=2021-10-31T23:22:41Z VendorInfo=debian:0.88.0-1
ERROR 2021/11/02 18:26:55 render of "taxonomy" failed: execute of template failed: template: _default/terms.html:1:3: executing "_default/terms.html" at <partial "header" .>: error calling partial: execute of template failed: template: partials/header.html:7:5: executing "partials/header.html" at <partial "meta" .>: error calling partial: "/home/sylvestre/dev/debian/pkg-llvm/llvm-blog-www/themes/hugo-kiera/layouts/partials/meta.html:6:96": execute of template failed: template: partials/meta.html:6:96: executing "partials/meta.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type

```

**Comment by lattner** [comment]
This looks really great to me Sylvestre!  @tlattner do you have any advice on testing the images?  If not, we can just land it and fix it in realtime if needed.

**Comment by sylvestre** [comment]
@lattner @tlattner I modified the html page locally to provide the right path for the images, it looks good to me!
Depending at what time it ships, I am also available to debug live :)

**Comment by lattner** [comment]
@sylvestre do you have commit access to this repo?  Feel free to merge when you're able to live debug :-)

**Comment by sylvestre** [comment]
@lattner I don't have permission unfortunately :)

**Comment by lattner** [comment]
Looks great!

**Comment by sylvestre** [comment]
\o/
many thanks!

**Pull request merged**
