### PR TITLE
Blog Post to highlight "Google Summer of Code 2023 Contributions for LLVM"

### PR DESCRIPTION
**Pull request by QuillPusher**
- I talked to some of the contributors to the LLVM GSoC program to highlight their accomplishments.

- I have tested this locally on Hugo

- I have gone through the [contribution guide](https: //llvm.org/docs/GitHub.html#github-reviews), please let me know if I missed something

### CODE REVIEW

**Comment by asl** [comment]
Thanks for doing this! Soon we will have a generic GSoC 2023-related post. So we will think how to structure all follow-up reports

**Comment by QuillPusher** [comment]
Hello @asl , Do you mean to say that this article on its own would be redundant (given that a generic article is also on its way)?

Let me add some context here. 

I worked with Compiler Research Org this year as a **Technical Writer for their Google Season of Docs program**, and I was able to work alongside the GSoC students that have been covered in this article and I created [detailed documentation](https://compiler-research.org/assets/docs/gsod_casestudy_2023.pdf) for these efforts. This blog is a summarization of those efforts.

Besides student developers' contribution to the LLVM community, this article also highlights the **mentorship efforts by the folks at Compiler Research Organization.**

We also had a similar year-end [Blog Post](https://blog.llvm.org/posts/2022-12-21-compiler-research-internships/) by our previous technical writer last year.

Please let me know your thoughts on this (and Happy New Year!)

**Comment by asl** [comment]
@QuillPusher It won't be obsolete (though the students were supposed to write blog posts by themselves), however, I would probably ask you to shorten it and change the format slightly. As generic things (e.g. list of projects) will be covered by the "main" blog post

**Comment by QuillPusher** [comment]
Thanks @asl for the insights, please see if this looks OK now :)

**Comment by QuillPusher** [comment]
Hello @asl 
Please review the changes when you get a chance

**Comment by QuillPusher** [comment]
Hello @asl , any progress on this?

**Comment by QuillPusher** [comment]
Hello @asl 

Any feedback on this?

**Comment by asl** [comment]
@QuillPusher Sorry for the silence. Will merge after https://github.com/llvm/llvm-blog-www/pull/50 will go out adding cross-links, etc.

Thanks!

**Comment by QuillPusher** [comment]
Thanks for the help @asl , the post looks good 😃

**Pull request merged**
