### PR TITLE
LLVM-centric internships accomplishments by Compiler-Research contributors

### PR DESCRIPTION
**Pull request by sarabellei**
This pull request focuses on a new blog post called "Interactive programming in C++ internships". 

The blog post describes the accomplishments of six interns from the Compiler-Research group. The six young developers worked on seven projects covering a range of topics that lead toward the common goal to improve support for interactive C++ in the LLVM environment. 

The blog post includes links to 2022 LLVM Developers' Meeting's videos. 

@vgvassilev

### CODE REVIEW

**Comment by vgvassilev** [comment]
This PR looks good to me.

@sarabellei is our technical writer who captured the progress of our group during the summer on various LLVM-based projects in the area of interactive C++. We thought it would be a good idea to inform the community about this and popularize a little more the summer internships that could be done around LLVM.

**Comment by lattner** [comment]
This blog post looks really great to me @sarabellei (and @vgvassilev), thank you!  My one request is that you clarify the intro, it starts with:

"Another program year is ending and we are extremely happy to share the hard work and the results of our interns contributors!"

This will be on the LLVM blog, so it sounds like it is the llvm project speaking.  I'd add a few sentences to introduce your group for those who are not familiar with it before jumping in.

Also, with the holidays, I'd recommend posting waiting to post this in early Jan because it will get more attention when people are back etc.

**Comment by sarabellei** [comment]
Hi @lattner, thank you for your feedback. I implemented your suggestion!

**Comment by lattner** [comment]
Awesome, I'll merge it, thank you @sarabellei !

**Pull request merged**
