### PR TITLE
Add a blog post about Cling -- Beyond Just Interpreting C++.

### PR DESCRIPTION
**Pull request by vgvassilev**
And some other minor typos in the previous cling blog posts.

### CODE REVIEW

**Comment by lattner** [comment]
Hey @vgvassilev thank you for writing this.  Could you split the unrelated patch out of 2021-03-25-cling-beyond-just-interpreting-cpp.md?  I'm happy to apply those right away.

**Comment by lattner** [comment]
Overall, this post looks really awesome to me - no concerns at all.  @tlattner do you have any concerns or is this good to go?

**Comment by vgvassilev** [comment]
Hi @lattner, sure thing -- that's PR #20

**Comment by tlattner** [comment]
> Overall, this post looks really awesome to me - no concerns at all. @tlattner do you have any concerns or is this good to go?

Looks ok to me

**Comment by lattner** [comment]
thanks Vassil, great post!

**Comment by vgvassilev** [comment]
Thanks Chris and Tanya!

**Pull request merged**
