### PR TITLE
Add post about the security group and its transparency report.

### PR DESCRIPTION
**Pull request by kbeyls**

### CODE REVIEW

**Comment by lattner** [comment]
This looks great to me Kristof, feel free to merge it whenever you think it makes sense!

**Review by lattner — APPROVED** [review]

**Comment by kbeyls** [comment]
Thanks for the review Chris! I'm afraid I don't have rights to merge. Could you merge it?

**Comment by lattner** [comment]
Yep, done!  @tlattner FYI, it would be good to get Kristof access to the blog

**Comment by tlattner** [comment]
Kristof is now an admin.

-Tanya

**Pull request merged**
