### PR TITLE
Add blog post for constructor homing for debug info

### PR DESCRIPTION
**Pull request by amykhuang**

### CODE REVIEW

**Review by lattner — APPROVED** [review]

**Comment by lattner** [comment]
Sorry for the delay, this post looks really great @amykhuang .  Would you prefer to post it ASAP (ie today), wait until Monday, or some other time?

**Comment by amykhuang** [comment]
Thanks, Monday is fine!

**Comment by lattner** [comment]
Will do, thanks again!

**Comment by lattner** [comment]
I'm sorry for the delay, this is live!

**Comment by hahnjo** [comment]
Hm, `title:  The New Pass Manager` looks odd. If that gets fixed, you should probably also remove the first heading.

/cc @lattner @amykhuang

**Comment by amykhuang** [comment]
Whoops, made a pr to fix that -

**Pull request merged**
