### PR TITLE
Byte types, or how to get rid of i8 abuse for chars in LLVM IR

### PR DESCRIPTION
**Pull request by georgemitenkov**

### CODE REVIEW

**Comment by lattner** [comment]
Hey @georgemitenkov I love this writeup, this is really great summary of a complicated topic and thread.  That said, I don't think that posting this on the blog is the right way to go.  The LLVM blog is effectively a marketing tool, which we use to raise visibility for things going on in the project to people outside the problem.

This doc is effectively a fancy RFC trying to inspire progress on an issue.  I think it would/could make tons of sense to have a blog post about this work, but only after the community gains consensus.  More like a post-mortem than a pre-mortem.  Does that make sense to you?

**Comment by lattner** [comment]
Thank you George!

**Comment by lattner** [comment]
One super easy way to do this is to drop it into your github "gists".  I've done that for long term things such as this, and it has worked well:
https://gist.github.com/lattner/31ed37682ef1576b16bca1432ea9f782

**Comment by georgemitenkov** [comment]
Thanks for the tip! This is indeed a super easy way.

**Pull request closed without merging**
